/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as KyafIndexImport } from './routes/kyaf/index'
import { Route as BkkkIndexImport } from './routes/bk/index'
import { Route as KyafVisitImport } from './routes/kyaf/visit'
import { Route as KyafTeamImport } from './routes/kyaf/team'
import { Route as KyafSupportImport } from './routes/kyaf/support'
import { Route as KyafShopImport } from './routes/kyaf/shop'
import { Route as KyafResidencyImport } from './routes/kyaf/residency'
import { Route as KyafPressImport } from './routes/kyaf/press'
import { Route as KyafNewsImport } from './routes/kyaf/news'
import { Route as KyafHiddenAssetsImport } from './routes/kyaf/hidden-assets'
import { Route as KyafContactImport } from './routes/kyaf/contact'
import { Route as KyafArchivesImport } from './routes/kyaf/archives'
import { Route as KyaflayoutImport } from './routes/kyaf/__layout'
import { Route as BkkkVisitImport } from './routes/bk/visit'
import { Route as BkkkTeamImport } from './routes/bk/team'
import { Route as BkkkSupportImport } from './routes/bk/support'
import { Route as BkkkShopImport } from './routes/bk/shop'
import { Route as BkkkResidencyImport } from './routes/bk/residency'
import { Route as BkkkPressImport } from './routes/bk/press'
import { Route as BkkkNewsImport } from './routes/bk/news'
import { Route as BkkkHiddenAssetsImport } from './routes/bk/hidden-assets'
import { Route as BkkkContactImport } from './routes/bk/contact'
import { Route as BkkkArchivesImport } from './routes/bk/archives'
import { Route as BkkklayoutImport } from './routes/bk/__layout'
import { Route as KyafExhibitionsIndexImport } from './routes/kyaf/exhibitions/index'
import { Route as KyafBlogIndexImport } from './routes/kyaf/blog/index'
import { Route as KyafActivitiesIndexImport } from './routes/kyaf/activities/index'
import { Route as KyafAboutIndexImport } from './routes/kyaf/about/index'
import { Route as BkkkMovingImageIndexImport } from './routes/bk/moving-image/index'
import { Route as BkkkExhibitionsIndexImport } from './routes/bk/exhibitions/index'
import { Route as BkkkBlogIndexImport } from './routes/bk/blog/index'
import { Route as BkkkActivitiesIndexImport } from './routes/bk/activities/index'
import { Route as BkkkAboutIndexImport } from './routes/bk/about/index'
import { Route as KyafExhibitionsSlugImport } from './routes/kyaf/exhibitions/$slug'
import { Route as KyafBlogSlugImport } from './routes/kyaf/blog/$slug'
import { Route as KyafArtistsSlugImport } from './routes/kyaf/artists/$slug'
import { Route as KyafActivitiesSlugImport } from './routes/kyaf/activities/$slug'
import { Route as KyafAboutVisionImport } from './routes/kyaf/about/vision'
import { Route as KyafAboutHistoryImport } from './routes/kyaf/about/history'
import { Route as BkkkMovingImageSlugImport } from './routes/bk/moving-image/$slug'
import { Route as BkkkExhibitionsSlugImport } from './routes/bk/exhibitions/$slug'
import { Route as BkkkBlogSlugImport } from './routes/bk/blog/$slug'
import { Route as BkkkArtistsSlugImport } from './routes/bk/artists/$slug'
import { Route as BkkkActivitiesSlugImport } from './routes/bk/activities/$slug'
import { Route as BkkkAboutVisionImport } from './routes/bk/about/vision'
import { Route as BkkkAboutHistoryImport } from './routes/bk/about/history'

// Create Virtual Routes

const KyafImport = createFileRoute('/kyaf')()
const BkkkImport = createFileRoute('/bk')()

// Create/Update Routes

const KyafRoute = KyafImport.update({
  id: '/kyaf',
  path: '/kyaf',
  getParentRoute: () => rootRoute,
} as any)

const BkkkRoute = BkkkImport.update({
  id: '/bk',
  path: '/bk',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const KyafIndexRoute = KyafIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const BkkkIndexRoute = BkkkIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const KyafVisitRoute = KyafVisitImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafTeamRoute = KyafTeamImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafSupportRoute = KyafSupportImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafShopRoute = KyafShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafResidencyRoute = KyafResidencyImport.update({
  id: '/residency',
  path: '/residency',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafPressRoute = KyafPressImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafNewsRoute = KyafNewsImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafHiddenAssetsRoute = KyafHiddenAssetsImport.update({
  id: '/hidden-assets',
  path: '/hidden-assets',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafContactRoute = KyafContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafArchivesRoute = KyafArchivesImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyaflayoutRoute = KyaflayoutImport.update({
  id: '/__layout',
  getParentRoute: () => KyafRoute,
} as any)

const BkkkVisitRoute = BkkkVisitImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkTeamRoute = BkkkTeamImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkSupportRoute = BkkkSupportImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkShopRoute = BkkkShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkResidencyRoute = BkkkResidencyImport.update({
  id: '/residency',
  path: '/residency',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkPressRoute = BkkkPressImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkNewsRoute = BkkkNewsImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkHiddenAssetsRoute = BkkkHiddenAssetsImport.update({
  id: '/hidden-assets',
  path: '/hidden-assets',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkContactRoute = BkkkContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkArchivesRoute = BkkkArchivesImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkklayoutRoute = BkkklayoutImport.update({
  id: '/__layout',
  getParentRoute: () => BkkkRoute,
} as any)

const KyafExhibitionsIndexRoute = KyafExhibitionsIndexImport.update({
  id: '/exhibitions/',
  path: '/exhibitions/',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafBlogIndexRoute = KyafBlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafActivitiesIndexRoute = KyafActivitiesIndexImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafAboutIndexRoute = KyafAboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const BkkkMovingImageIndexRoute = BkkkMovingImageIndexImport.update({
  id: '/moving-image/',
  path: '/moving-image/',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkExhibitionsIndexRoute = BkkkExhibitionsIndexImport.update({
  id: '/exhibitions/',
  path: '/exhibitions/',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkBlogIndexRoute = BkkkBlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkActivitiesIndexRoute = BkkkActivitiesIndexImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkAboutIndexRoute = BkkkAboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const KyafExhibitionsSlugRoute = KyafExhibitionsSlugImport.update({
  id: '/exhibitions/$slug',
  path: '/exhibitions/$slug',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafBlogSlugRoute = KyafBlogSlugImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafArtistsSlugRoute = KyafArtistsSlugImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafActivitiesSlugRoute = KyafActivitiesSlugImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafAboutVisionRoute = KyafAboutVisionImport.update({
  id: '/about/vision',
  path: '/about/vision',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const KyafAboutHistoryRoute = KyafAboutHistoryImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => KyaflayoutRoute,
} as any)

const BkkkMovingImageSlugRoute = BkkkMovingImageSlugImport.update({
  id: '/moving-image/$slug',
  path: '/moving-image/$slug',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkExhibitionsSlugRoute = BkkkExhibitionsSlugImport.update({
  id: '/exhibitions/$slug',
  path: '/exhibitions/$slug',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkBlogSlugRoute = BkkkBlogSlugImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkArtistsSlugRoute = BkkkArtistsSlugImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkActivitiesSlugRoute = BkkkActivitiesSlugImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkAboutVisionRoute = BkkkAboutVisionImport.update({
  id: '/about/vision',
  path: '/about/vision',
  getParentRoute: () => BkkklayoutRoute,
} as any)

const BkkkAboutHistoryRoute = BkkkAboutHistoryImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => BkkklayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bk': {
      id: '/bk'
      path: '/bk'
      fullPath: '/bk'
      preLoaderRoute: typeof BkkkImport
      parentRoute: typeof rootRoute
    }
    '/bk/__layout': {
      id: '/bk/__layout'
      path: '/bk'
      fullPath: '/bk'
      preLoaderRoute: typeof BkkklayoutImport
      parentRoute: typeof BkkkRoute
    }
    '/bk/archives': {
      id: '/bk/archives'
      path: '/archives'
      fullPath: '/bk/archives'
      preLoaderRoute: typeof BkkkArchivesImport
      parentRoute: typeof BkkkImport
    }
    '/bk/contact': {
      id: '/bk/contact'
      path: '/contact'
      fullPath: '/bk/contact'
      preLoaderRoute: typeof BkkkContactImport
      parentRoute: typeof BkkkImport
    }
    '/bk/hidden-assets': {
      id: '/bk/hidden-assets'
      path: '/hidden-assets'
      fullPath: '/bk/hidden-assets'
      preLoaderRoute: typeof BkkkHiddenAssetsImport
      parentRoute: typeof BkkkImport
    }
    '/bk/news': {
      id: '/bk/news'
      path: '/news'
      fullPath: '/bk/news'
      preLoaderRoute: typeof BkkkNewsImport
      parentRoute: typeof BkkkImport
    }
    '/bk/press': {
      id: '/bk/press'
      path: '/press'
      fullPath: '/bk/press'
      preLoaderRoute: typeof BkkkPressImport
      parentRoute: typeof BkkkImport
    }
    '/bk/residency': {
      id: '/bk/residency'
      path: '/residency'
      fullPath: '/bk/residency'
      preLoaderRoute: typeof BkkkResidencyImport
      parentRoute: typeof BkkkImport
    }
    '/bk/shop': {
      id: '/bk/shop'
      path: '/shop'
      fullPath: '/bk/shop'
      preLoaderRoute: typeof BkkkShopImport
      parentRoute: typeof BkkkImport
    }
    '/bk/support': {
      id: '/bk/support'
      path: '/support'
      fullPath: '/bk/support'
      preLoaderRoute: typeof BkkkSupportImport
      parentRoute: typeof BkkkImport
    }
    '/bk/team': {
      id: '/bk/team'
      path: '/team'
      fullPath: '/bk/team'
      preLoaderRoute: typeof BkkkTeamImport
      parentRoute: typeof BkkkImport
    }
    '/bk/visit': {
      id: '/bk/visit'
      path: '/visit'
      fullPath: '/bk/visit'
      preLoaderRoute: typeof BkkkVisitImport
      parentRoute: typeof BkkkImport
    }
    '/kyaf': {
      id: '/kyaf'
      path: '/kyaf'
      fullPath: '/kyaf'
      preLoaderRoute: typeof KyafImport
      parentRoute: typeof rootRoute
    }
    '/kyaf/__layout': {
      id: '/kyaf/__layout'
      path: '/kyaf'
      fullPath: '/kyaf'
      preLoaderRoute: typeof KyaflayoutImport
      parentRoute: typeof KyafRoute
    }
    '/kyaf/archives': {
      id: '/kyaf/archives'
      path: '/archives'
      fullPath: '/kyaf/archives'
      preLoaderRoute: typeof KyafArchivesImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/contact': {
      id: '/kyaf/contact'
      path: '/contact'
      fullPath: '/kyaf/contact'
      preLoaderRoute: typeof KyafContactImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/hidden-assets': {
      id: '/kyaf/hidden-assets'
      path: '/hidden-assets'
      fullPath: '/kyaf/hidden-assets'
      preLoaderRoute: typeof KyafHiddenAssetsImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/news': {
      id: '/kyaf/news'
      path: '/news'
      fullPath: '/kyaf/news'
      preLoaderRoute: typeof KyafNewsImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/press': {
      id: '/kyaf/press'
      path: '/press'
      fullPath: '/kyaf/press'
      preLoaderRoute: typeof KyafPressImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/residency': {
      id: '/kyaf/residency'
      path: '/residency'
      fullPath: '/kyaf/residency'
      preLoaderRoute: typeof KyafResidencyImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/shop': {
      id: '/kyaf/shop'
      path: '/shop'
      fullPath: '/kyaf/shop'
      preLoaderRoute: typeof KyafShopImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/support': {
      id: '/kyaf/support'
      path: '/support'
      fullPath: '/kyaf/support'
      preLoaderRoute: typeof KyafSupportImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/team': {
      id: '/kyaf/team'
      path: '/team'
      fullPath: '/kyaf/team'
      preLoaderRoute: typeof KyafTeamImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/visit': {
      id: '/kyaf/visit'
      path: '/visit'
      fullPath: '/kyaf/visit'
      preLoaderRoute: typeof KyafVisitImport
      parentRoute: typeof KyafImport
    }
    '/bk/': {
      id: '/bk/'
      path: '/'
      fullPath: '/bk/'
      preLoaderRoute: typeof BkkkIndexImport
      parentRoute: typeof BkkkImport
    }
    '/kyaf/': {
      id: '/kyaf/'
      path: '/'
      fullPath: '/kyaf/'
      preLoaderRoute: typeof KyafIndexImport
      parentRoute: typeof KyafImport
    }
    '/bk/about/history': {
      id: '/bk/about/history'
      path: '/about/history'
      fullPath: '/bk/about/history'
      preLoaderRoute: typeof BkkkAboutHistoryImport
      parentRoute: typeof BkkkImport
    }
    '/bk/about/vision': {
      id: '/bk/about/vision'
      path: '/about/vision'
      fullPath: '/bk/about/vision'
      preLoaderRoute: typeof BkkkAboutVisionImport
      parentRoute: typeof BkkkImport
    }
    '/bk/activities/$slug': {
      id: '/bk/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/bk/activities/$slug'
      preLoaderRoute: typeof BkkkActivitiesSlugImport
      parentRoute: typeof BkkkImport
    }
    '/bk/artists/$slug': {
      id: '/bk/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/bk/artists/$slug'
      preLoaderRoute: typeof BkkkArtistsSlugImport
      parentRoute: typeof BkkkImport
    }
    '/bk/blog/$slug': {
      id: '/bk/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/bk/blog/$slug'
      preLoaderRoute: typeof BkkkBlogSlugImport
      parentRoute: typeof BkkkImport
    }
    '/bk/exhibitions/$slug': {
      id: '/bk/exhibitions/$slug'
      path: '/exhibitions/$slug'
      fullPath: '/bk/exhibitions/$slug'
      preLoaderRoute: typeof BkkkExhibitionsSlugImport
      parentRoute: typeof BkkkImport
    }
    '/bk/moving-image/$slug': {
      id: '/bk/moving-image/$slug'
      path: '/moving-image/$slug'
      fullPath: '/bk/moving-image/$slug'
      preLoaderRoute: typeof BkkkMovingImageSlugImport
      parentRoute: typeof BkkkImport
    }
    '/kyaf/about/history': {
      id: '/kyaf/about/history'
      path: '/about/history'
      fullPath: '/kyaf/about/history'
      preLoaderRoute: typeof KyafAboutHistoryImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/about/vision': {
      id: '/kyaf/about/vision'
      path: '/about/vision'
      fullPath: '/kyaf/about/vision'
      preLoaderRoute: typeof KyafAboutVisionImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/activities/$slug': {
      id: '/kyaf/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/kyaf/activities/$slug'
      preLoaderRoute: typeof KyafActivitiesSlugImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/artists/$slug': {
      id: '/kyaf/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/kyaf/artists/$slug'
      preLoaderRoute: typeof KyafArtistsSlugImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/blog/$slug': {
      id: '/kyaf/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/kyaf/blog/$slug'
      preLoaderRoute: typeof KyafBlogSlugImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/exhibitions/$slug': {
      id: '/kyaf/exhibitions/$slug'
      path: '/exhibitions/$slug'
      fullPath: '/kyaf/exhibitions/$slug'
      preLoaderRoute: typeof KyafExhibitionsSlugImport
      parentRoute: typeof KyafImport
    }
    '/bk/about/': {
      id: '/bk/about/'
      path: '/about'
      fullPath: '/bk/about'
      preLoaderRoute: typeof BkkkAboutIndexImport
      parentRoute: typeof BkkkImport
    }
    '/bk/activities/': {
      id: '/bk/activities/'
      path: '/activities'
      fullPath: '/bk/activities'
      preLoaderRoute: typeof BkkkActivitiesIndexImport
      parentRoute: typeof BkkkImport
    }
    '/bk/blog/': {
      id: '/bk/blog/'
      path: '/blog'
      fullPath: '/bk/blog'
      preLoaderRoute: typeof BkkkBlogIndexImport
      parentRoute: typeof BkkkImport
    }
    '/bk/exhibitions/': {
      id: '/bk/exhibitions/'
      path: '/exhibitions'
      fullPath: '/bk/exhibitions'
      preLoaderRoute: typeof BkkkExhibitionsIndexImport
      parentRoute: typeof BkkkImport
    }
    '/bk/moving-image/': {
      id: '/bk/moving-image/'
      path: '/moving-image'
      fullPath: '/bk/moving-image'
      preLoaderRoute: typeof BkkkMovingImageIndexImport
      parentRoute: typeof BkkkImport
    }
    '/kyaf/about/': {
      id: '/kyaf/about/'
      path: '/about'
      fullPath: '/kyaf/about'
      preLoaderRoute: typeof KyafAboutIndexImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/activities/': {
      id: '/kyaf/activities/'
      path: '/activities'
      fullPath: '/kyaf/activities'
      preLoaderRoute: typeof KyafActivitiesIndexImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/blog/': {
      id: '/kyaf/blog/'
      path: '/blog'
      fullPath: '/kyaf/blog'
      preLoaderRoute: typeof KyafBlogIndexImport
      parentRoute: typeof KyafImport
    }
    '/kyaf/exhibitions/': {
      id: '/kyaf/exhibitions/'
      path: '/exhibitions'
      fullPath: '/kyaf/exhibitions'
      preLoaderRoute: typeof KyafExhibitionsIndexImport
      parentRoute: typeof KyafImport
    }
  }
}

// Create and export the route tree

interface BkkkRouteChildren {
  BkkklayoutRoute: typeof BkkklayoutRoute
  BkkkArchivesRoute: typeof BkkkArchivesRoute
  BkkkContactRoute: typeof BkkkContactRoute
  BkkkHiddenAssetsRoute: typeof BkkkHiddenAssetsRoute
  BkkkNewsRoute: typeof BkkkNewsRoute
  BkkkPressRoute: typeof BkkkPressRoute
  BkkkResidencyRoute: typeof BkkkResidencyRoute
  BkkkShopRoute: typeof BkkkShopRoute
  BkkkSupportRoute: typeof BkkkSupportRoute
  BkkkTeamRoute: typeof BkkkTeamRoute
  BkkkVisitRoute: typeof BkkkVisitRoute
  BkkkIndexRoute: typeof BkkkIndexRoute
  BkkkAboutHistoryRoute: typeof BkkkAboutHistoryRoute
  BkkkAboutVisionRoute: typeof BkkkAboutVisionRoute
  BkkkActivitiesSlugRoute: typeof BkkkActivitiesSlugRoute
  BkkkArtistsSlugRoute: typeof BkkkArtistsSlugRoute
  BkkkBlogSlugRoute: typeof BkkkBlogSlugRoute
  BkkkExhibitionsSlugRoute: typeof BkkkExhibitionsSlugRoute
  BkkkMovingImageSlugRoute: typeof BkkkMovingImageSlugRoute
  BkkkAboutIndexRoute: typeof BkkkAboutIndexRoute
  BkkkActivitiesIndexRoute: typeof BkkkActivitiesIndexRoute
  BkkkBlogIndexRoute: typeof BkkkBlogIndexRoute
  BkkkExhibitionsIndexRoute: typeof BkkkExhibitionsIndexRoute
  BkkkMovingImageIndexRoute: typeof BkkkMovingImageIndexRoute
}

const BkkkRouteChildren: BkkkRouteChildren = {
  BkkklayoutRoute: BkkklayoutRoute,
  BkkkArchivesRoute: BkkkArchivesRoute,
  BkkkContactRoute: BkkkContactRoute,
  BkkkHiddenAssetsRoute: BkkkHiddenAssetsRoute,
  BkkkNewsRoute: BkkkNewsRoute,
  BkkkPressRoute: BkkkPressRoute,
  BkkkResidencyRoute: BkkkResidencyRoute,
  BkkkShopRoute: BkkkShopRoute,
  BkkkSupportRoute: BkkkSupportRoute,
  BkkkTeamRoute: BkkkTeamRoute,
  BkkkVisitRoute: BkkkVisitRoute,
  BkkkIndexRoute: BkkkIndexRoute,
  BkkkAboutHistoryRoute: BkkkAboutHistoryRoute,
  BkkkAboutVisionRoute: BkkkAboutVisionRoute,
  BkkkActivitiesSlugRoute: BkkkActivitiesSlugRoute,
  BkkkArtistsSlugRoute: BkkkArtistsSlugRoute,
  BkkkBlogSlugRoute: BkkkBlogSlugRoute,
  BkkkExhibitionsSlugRoute: BkkkExhibitionsSlugRoute,
  BkkkMovingImageSlugRoute: BkkkMovingImageSlugRoute,
  BkkkAboutIndexRoute: BkkkAboutIndexRoute,
  BkkkActivitiesIndexRoute: BkkkActivitiesIndexRoute,
  BkkkBlogIndexRoute: BkkkBlogIndexRoute,
  BkkkExhibitionsIndexRoute: BkkkExhibitionsIndexRoute,
  BkkkMovingImageIndexRoute: BkkkMovingImageIndexRoute,
}

const BkkkRouteWithChildren = BkkkRoute._addFileChildren(BkkkRouteChildren)

interface KyafRouteChildren {
  KyaflayoutRoute: typeof KyaflayoutRoute
  KyafArchivesRoute: typeof KyafArchivesRoute
  KyafContactRoute: typeof KyafContactRoute
  KyafHiddenAssetsRoute: typeof KyafHiddenAssetsRoute
  KyafNewsRoute: typeof KyafNewsRoute
  KyafPressRoute: typeof KyafPressRoute
  KyafResidencyRoute: typeof KyafResidencyRoute
  KyafShopRoute: typeof KyafShopRoute
  KyafSupportRoute: typeof KyafSupportRoute
  KyafTeamRoute: typeof KyafTeamRoute
  KyafVisitRoute: typeof KyafVisitRoute
  KyafIndexRoute: typeof KyafIndexRoute
  KyafAboutHistoryRoute: typeof KyafAboutHistoryRoute
  KyafAboutVisionRoute: typeof KyafAboutVisionRoute
  KyafActivitiesSlugRoute: typeof KyafActivitiesSlugRoute
  KyafArtistsSlugRoute: typeof KyafArtistsSlugRoute
  KyafBlogSlugRoute: typeof KyafBlogSlugRoute
  KyafExhibitionsSlugRoute: typeof KyafExhibitionsSlugRoute
  KyafAboutIndexRoute: typeof KyafAboutIndexRoute
  KyafActivitiesIndexRoute: typeof KyafActivitiesIndexRoute
  KyafBlogIndexRoute: typeof KyafBlogIndexRoute
  KyafExhibitionsIndexRoute: typeof KyafExhibitionsIndexRoute
}

const KyafRouteChildren: KyafRouteChildren = {
  KyaflayoutRoute: KyaflayoutRoute,
  KyafArchivesRoute: KyafArchivesRoute,
  KyafContactRoute: KyafContactRoute,
  KyafHiddenAssetsRoute: KyafHiddenAssetsRoute,
  KyafNewsRoute: KyafNewsRoute,
  KyafPressRoute: KyafPressRoute,
  KyafResidencyRoute: KyafResidencyRoute,
  KyafShopRoute: KyafShopRoute,
  KyafSupportRoute: KyafSupportRoute,
  KyafTeamRoute: KyafTeamRoute,
  KyafVisitRoute: KyafVisitRoute,
  KyafIndexRoute: KyafIndexRoute,
  KyafAboutHistoryRoute: KyafAboutHistoryRoute,
  KyafAboutVisionRoute: KyafAboutVisionRoute,
  KyafActivitiesSlugRoute: KyafActivitiesSlugRoute,
  KyafArtistsSlugRoute: KyafArtistsSlugRoute,
  KyafBlogSlugRoute: KyafBlogSlugRoute,
  KyafExhibitionsSlugRoute: KyafExhibitionsSlugRoute,
  KyafAboutIndexRoute: KyafAboutIndexRoute,
  KyafActivitiesIndexRoute: KyafActivitiesIndexRoute,
  KyafBlogIndexRoute: KyafBlogIndexRoute,
  KyafExhibitionsIndexRoute: KyafExhibitionsIndexRoute,
}

const KyafRouteWithChildren = KyafRoute._addFileChildren(KyafRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bk': typeof BkkklayoutRoute
  '/bk/archives': typeof BkkkArchivesRoute
  '/bk/contact': typeof BkkkContactRoute
  '/bk/hidden-assets': typeof BkkkHiddenAssetsRoute
  '/bk/news': typeof BkkkNewsRoute
  '/bk/press': typeof BkkkPressRoute
  '/bk/residency': typeof BkkkResidencyRoute
  '/bk/shop': typeof BkkkShopRoute
  '/bk/support': typeof BkkkSupportRoute
  '/bk/team': typeof BkkkTeamRoute
  '/bk/visit': typeof BkkkVisitRoute
  '/kyaf': typeof KyaflayoutRoute
  '/kyaf/archives': typeof KyafArchivesRoute
  '/kyaf/contact': typeof KyafContactRoute
  '/kyaf/hidden-assets': typeof KyafHiddenAssetsRoute
  '/kyaf/news': typeof KyafNewsRoute
  '/kyaf/press': typeof KyafPressRoute
  '/kyaf/residency': typeof KyafResidencyRoute
  '/kyaf/shop': typeof KyafShopRoute
  '/kyaf/support': typeof KyafSupportRoute
  '/kyaf/team': typeof KyafTeamRoute
  '/kyaf/visit': typeof KyafVisitRoute
  '/bk/': typeof BkkkIndexRoute
  '/kyaf/': typeof KyafIndexRoute
  '/bk/about/history': typeof BkkkAboutHistoryRoute
  '/bk/about/vision': typeof BkkkAboutVisionRoute
  '/bk/activities/$slug': typeof BkkkActivitiesSlugRoute
  '/bk/artists/$slug': typeof BkkkArtistsSlugRoute
  '/bk/blog/$slug': typeof BkkkBlogSlugRoute
  '/bk/exhibitions/$slug': typeof BkkkExhibitionsSlugRoute
  '/bk/moving-image/$slug': typeof BkkkMovingImageSlugRoute
  '/kyaf/about/history': typeof KyafAboutHistoryRoute
  '/kyaf/about/vision': typeof KyafAboutVisionRoute
  '/kyaf/activities/$slug': typeof KyafActivitiesSlugRoute
  '/kyaf/artists/$slug': typeof KyafArtistsSlugRoute
  '/kyaf/blog/$slug': typeof KyafBlogSlugRoute
  '/kyaf/exhibitions/$slug': typeof KyafExhibitionsSlugRoute
  '/bk/about': typeof BkkkAboutIndexRoute
  '/bk/activities': typeof BkkkActivitiesIndexRoute
  '/bk/blog': typeof BkkkBlogIndexRoute
  '/bk/exhibitions': typeof BkkkExhibitionsIndexRoute
  '/bk/moving-image': typeof BkkkMovingImageIndexRoute
  '/kyaf/about': typeof KyafAboutIndexRoute
  '/kyaf/activities': typeof KyafActivitiesIndexRoute
  '/kyaf/blog': typeof KyafBlogIndexRoute
  '/kyaf/exhibitions': typeof KyafExhibitionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bk': typeof BkkkIndexRoute
  '/bk/archives': typeof BkkkArchivesRoute
  '/bk/contact': typeof BkkkContactRoute
  '/bk/hidden-assets': typeof BkkkHiddenAssetsRoute
  '/bk/news': typeof BkkkNewsRoute
  '/bk/press': typeof BkkkPressRoute
  '/bk/residency': typeof BkkkResidencyRoute
  '/bk/shop': typeof BkkkShopRoute
  '/bk/support': typeof BkkkSupportRoute
  '/bk/team': typeof BkkkTeamRoute
  '/bk/visit': typeof BkkkVisitRoute
  '/kyaf': typeof KyafIndexRoute
  '/kyaf/archives': typeof KyafArchivesRoute
  '/kyaf/contact': typeof KyafContactRoute
  '/kyaf/hidden-assets': typeof KyafHiddenAssetsRoute
  '/kyaf/news': typeof KyafNewsRoute
  '/kyaf/press': typeof KyafPressRoute
  '/kyaf/residency': typeof KyafResidencyRoute
  '/kyaf/shop': typeof KyafShopRoute
  '/kyaf/support': typeof KyafSupportRoute
  '/kyaf/team': typeof KyafTeamRoute
  '/kyaf/visit': typeof KyafVisitRoute
  '/bk/about/history': typeof BkkkAboutHistoryRoute
  '/bk/about/vision': typeof BkkkAboutVisionRoute
  '/bk/activities/$slug': typeof BkkkActivitiesSlugRoute
  '/bk/artists/$slug': typeof BkkkArtistsSlugRoute
  '/bk/blog/$slug': typeof BkkkBlogSlugRoute
  '/bk/exhibitions/$slug': typeof BkkkExhibitionsSlugRoute
  '/bk/moving-image/$slug': typeof BkkkMovingImageSlugRoute
  '/kyaf/about/history': typeof KyafAboutHistoryRoute
  '/kyaf/about/vision': typeof KyafAboutVisionRoute
  '/kyaf/activities/$slug': typeof KyafActivitiesSlugRoute
  '/kyaf/artists/$slug': typeof KyafArtistsSlugRoute
  '/kyaf/blog/$slug': typeof KyafBlogSlugRoute
  '/kyaf/exhibitions/$slug': typeof KyafExhibitionsSlugRoute
  '/bk/about': typeof BkkkAboutIndexRoute
  '/bk/activities': typeof BkkkActivitiesIndexRoute
  '/bk/blog': typeof BkkkBlogIndexRoute
  '/bk/exhibitions': typeof BkkkExhibitionsIndexRoute
  '/bk/moving-image': typeof BkkkMovingImageIndexRoute
  '/kyaf/about': typeof KyafAboutIndexRoute
  '/kyaf/activities': typeof KyafActivitiesIndexRoute
  '/kyaf/blog': typeof KyafBlogIndexRoute
  '/kyaf/exhibitions': typeof KyafExhibitionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bk': typeof BkkkRouteWithChildren
  '/bk/__layout': typeof BkkklayoutRoute
  '/bk/archives': typeof BkkkArchivesRoute
  '/bk/contact': typeof BkkkContactRoute
  '/bk/hidden-assets': typeof BkkkHiddenAssetsRoute
  '/bk/news': typeof BkkkNewsRoute
  '/bk/press': typeof BkkkPressRoute
  '/bk/residency': typeof BkkkResidencyRoute
  '/bk/shop': typeof BkkkShopRoute
  '/bk/support': typeof BkkkSupportRoute
  '/bk/team': typeof BkkkTeamRoute
  '/bk/visit': typeof BkkkVisitRoute
  '/kyaf': typeof KyafRouteWithChildren
  '/kyaf/__layout': typeof KyaflayoutRoute
  '/kyaf/archives': typeof KyafArchivesRoute
  '/kyaf/contact': typeof KyafContactRoute
  '/kyaf/hidden-assets': typeof KyafHiddenAssetsRoute
  '/kyaf/news': typeof KyafNewsRoute
  '/kyaf/press': typeof KyafPressRoute
  '/kyaf/residency': typeof KyafResidencyRoute
  '/kyaf/shop': typeof KyafShopRoute
  '/kyaf/support': typeof KyafSupportRoute
  '/kyaf/team': typeof KyafTeamRoute
  '/kyaf/visit': typeof KyafVisitRoute
  '/bk/': typeof BkkkIndexRoute
  '/kyaf/': typeof KyafIndexRoute
  '/bk/about/history': typeof BkkkAboutHistoryRoute
  '/bk/about/vision': typeof BkkkAboutVisionRoute
  '/bk/activities/$slug': typeof BkkkActivitiesSlugRoute
  '/bk/artists/$slug': typeof BkkkArtistsSlugRoute
  '/bk/blog/$slug': typeof BkkkBlogSlugRoute
  '/bk/exhibitions/$slug': typeof BkkkExhibitionsSlugRoute
  '/bk/moving-image/$slug': typeof BkkkMovingImageSlugRoute
  '/kyaf/about/history': typeof KyafAboutHistoryRoute
  '/kyaf/about/vision': typeof KyafAboutVisionRoute
  '/kyaf/activities/$slug': typeof KyafActivitiesSlugRoute
  '/kyaf/artists/$slug': typeof KyafArtistsSlugRoute
  '/kyaf/blog/$slug': typeof KyafBlogSlugRoute
  '/kyaf/exhibitions/$slug': typeof KyafExhibitionsSlugRoute
  '/bk/about/': typeof BkkkAboutIndexRoute
  '/bk/activities/': typeof BkkkActivitiesIndexRoute
  '/bk/blog/': typeof BkkkBlogIndexRoute
  '/bk/exhibitions/': typeof BkkkExhibitionsIndexRoute
  '/bk/moving-image/': typeof BkkkMovingImageIndexRoute
  '/kyaf/about/': typeof KyafAboutIndexRoute
  '/kyaf/activities/': typeof KyafActivitiesIndexRoute
  '/kyaf/blog/': typeof KyafBlogIndexRoute
  '/kyaf/exhibitions/': typeof KyafExhibitionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bk'
    | '/bk/archives'
    | '/bk/contact'
    | '/bk/hidden-assets'
    | '/bk/news'
    | '/bk/press'
    | '/bk/residency'
    | '/bk/shop'
    | '/bk/support'
    | '/bk/team'
    | '/bk/visit'
    | '/kyaf'
    | '/kyaf/archives'
    | '/kyaf/contact'
    | '/kyaf/hidden-assets'
    | '/kyaf/news'
    | '/kyaf/press'
    | '/kyaf/residency'
    | '/kyaf/shop'
    | '/kyaf/support'
    | '/kyaf/team'
    | '/kyaf/visit'
    | '/bk/'
    | '/kyaf/'
    | '/bk/about/history'
    | '/bk/about/vision'
    | '/bk/activities/$slug'
    | '/bk/artists/$slug'
    | '/bk/blog/$slug'
    | '/bk/exhibitions/$slug'
    | '/bk/moving-image/$slug'
    | '/kyaf/about/history'
    | '/kyaf/about/vision'
    | '/kyaf/activities/$slug'
    | '/kyaf/artists/$slug'
    | '/kyaf/blog/$slug'
    | '/kyaf/exhibitions/$slug'
    | '/bk/about'
    | '/bk/activities'
    | '/bk/blog'
    | '/bk/exhibitions'
    | '/bk/moving-image'
    | '/kyaf/about'
    | '/kyaf/activities'
    | '/kyaf/blog'
    | '/kyaf/exhibitions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bk'
    | '/bk/archives'
    | '/bk/contact'
    | '/bk/hidden-assets'
    | '/bk/news'
    | '/bk/press'
    | '/bk/residency'
    | '/bk/shop'
    | '/bk/support'
    | '/bk/team'
    | '/bk/visit'
    | '/kyaf'
    | '/kyaf/archives'
    | '/kyaf/contact'
    | '/kyaf/hidden-assets'
    | '/kyaf/news'
    | '/kyaf/press'
    | '/kyaf/residency'
    | '/kyaf/shop'
    | '/kyaf/support'
    | '/kyaf/team'
    | '/kyaf/visit'
    | '/bk/about/history'
    | '/bk/about/vision'
    | '/bk/activities/$slug'
    | '/bk/artists/$slug'
    | '/bk/blog/$slug'
    | '/bk/exhibitions/$slug'
    | '/bk/moving-image/$slug'
    | '/kyaf/about/history'
    | '/kyaf/about/vision'
    | '/kyaf/activities/$slug'
    | '/kyaf/artists/$slug'
    | '/kyaf/blog/$slug'
    | '/kyaf/exhibitions/$slug'
    | '/bk/about'
    | '/bk/activities'
    | '/bk/blog'
    | '/bk/exhibitions'
    | '/bk/moving-image'
    | '/kyaf/about'
    | '/kyaf/activities'
    | '/kyaf/blog'
    | '/kyaf/exhibitions'
  id:
    | '__root__'
    | '/'
    | '/bk'
    | '/bk/__layout'
    | '/bk/archives'
    | '/bk/contact'
    | '/bk/hidden-assets'
    | '/bk/news'
    | '/bk/press'
    | '/bk/residency'
    | '/bk/shop'
    | '/bk/support'
    | '/bk/team'
    | '/bk/visit'
    | '/kyaf'
    | '/kyaf/__layout'
    | '/kyaf/archives'
    | '/kyaf/contact'
    | '/kyaf/hidden-assets'
    | '/kyaf/news'
    | '/kyaf/press'
    | '/kyaf/residency'
    | '/kyaf/shop'
    | '/kyaf/support'
    | '/kyaf/team'
    | '/kyaf/visit'
    | '/bk/'
    | '/kyaf/'
    | '/bk/about/history'
    | '/bk/about/vision'
    | '/bk/activities/$slug'
    | '/bk/artists/$slug'
    | '/bk/blog/$slug'
    | '/bk/exhibitions/$slug'
    | '/bk/moving-image/$slug'
    | '/kyaf/about/history'
    | '/kyaf/about/vision'
    | '/kyaf/activities/$slug'
    | '/kyaf/artists/$slug'
    | '/kyaf/blog/$slug'
    | '/kyaf/exhibitions/$slug'
    | '/bk/about/'
    | '/bk/activities/'
    | '/bk/blog/'
    | '/bk/exhibitions/'
    | '/bk/moving-image/'
    | '/kyaf/about/'
    | '/kyaf/activities/'
    | '/kyaf/blog/'
    | '/kyaf/exhibitions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BkkkRoute: typeof BkkkRouteWithChildren
  KyafRoute: typeof KyafRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BkkkRoute: BkkkRouteWithChildren,
  KyafRoute: KyafRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bk",
        "/kyaf"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bk": {
      "filePath": "bk",
      "children": [
        "/bk/__layout",
        "/bk/archives",
        "/bk/contact",
        "/bk/hidden-assets",
        "/bk/news",
        "/bk/press",
        "/bk/residency",
        "/bk/shop",
        "/bk/support",
        "/bk/team",
        "/bk/visit",
        "/bk/",
        "/bk/about/history",
        "/bk/about/vision",
        "/bk/activities/$slug",
        "/bk/artists/$slug",
        "/bk/blog/$slug",
        "/bk/exhibitions/$slug",
        "/bk/moving-image/$slug",
        "/bk/about/",
        "/bk/activities/",
        "/bk/blog/",
        "/bk/exhibitions/",
        "/bk/moving-image/"
      ]
    },
    "/bk/__layout": {
      "filePath": "bk/__layout.tsx",
      "parent": "/bk"
    },
    "/bk/archives": {
      "filePath": "bk/archives.tsx",
      "parent": "/bk"
    },
    "/bk/contact": {
      "filePath": "bk/contact.tsx",
      "parent": "/bk"
    },
    "/bk/hidden-assets": {
      "filePath": "bk/hidden-assets.tsx",
      "parent": "/bk"
    },
    "/bk/news": {
      "filePath": "bk/news.tsx",
      "parent": "/bk"
    },
    "/bk/press": {
      "filePath": "bk/press.tsx",
      "parent": "/bk"
    },
    "/bk/residency": {
      "filePath": "bk/residency.tsx",
      "parent": "/bk"
    },
    "/bk/shop": {
      "filePath": "bk/shop.tsx",
      "parent": "/bk"
    },
    "/bk/support": {
      "filePath": "bk/support.tsx",
      "parent": "/bk"
    },
    "/bk/team": {
      "filePath": "bk/team.tsx",
      "parent": "/bk"
    },
    "/bk/visit": {
      "filePath": "bk/visit.tsx",
      "parent": "/bk"
    },
    "/kyaf": {
      "filePath": "kyaf",
      "children": [
        "/kyaf/__layout",
        "/kyaf/archives",
        "/kyaf/contact",
        "/kyaf/hidden-assets",
        "/kyaf/news",
        "/kyaf/press",
        "/kyaf/residency",
        "/kyaf/shop",
        "/kyaf/support",
        "/kyaf/team",
        "/kyaf/visit",
        "/kyaf/",
        "/kyaf/about/history",
        "/kyaf/about/vision",
        "/kyaf/activities/$slug",
        "/kyaf/artists/$slug",
        "/kyaf/blog/$slug",
        "/kyaf/exhibitions/$slug",
        "/kyaf/about/",
        "/kyaf/activities/",
        "/kyaf/blog/",
        "/kyaf/exhibitions/"
      ]
    },
    "/kyaf/__layout": {
      "filePath": "kyaf/__layout.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/archives": {
      "filePath": "kyaf/archives.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/contact": {
      "filePath": "kyaf/contact.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/hidden-assets": {
      "filePath": "kyaf/hidden-assets.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/news": {
      "filePath": "kyaf/news.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/press": {
      "filePath": "kyaf/press.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/residency": {
      "filePath": "kyaf/residency.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/shop": {
      "filePath": "kyaf/shop.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/support": {
      "filePath": "kyaf/support.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/team": {
      "filePath": "kyaf/team.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/visit": {
      "filePath": "kyaf/visit.tsx",
      "parent": "/kyaf"
    },
    "/bk/": {
      "filePath": "bk/index.tsx",
      "parent": "/bk"
    },
    "/kyaf/": {
      "filePath": "kyaf/index.tsx",
      "parent": "/kyaf"
    },
    "/bk/about/history": {
      "filePath": "bk/about/history.tsx",
      "parent": "/bk"
    },
    "/bk/about/vision": {
      "filePath": "bk/about/vision.tsx",
      "parent": "/bk"
    },
    "/bk/activities/$slug": {
      "filePath": "bk/activities/$slug.tsx",
      "parent": "/bk"
    },
    "/bk/artists/$slug": {
      "filePath": "bk/artists/$slug.tsx",
      "parent": "/bk"
    },
    "/bk/blog/$slug": {
      "filePath": "bk/blog/$slug.tsx",
      "parent": "/bk"
    },
    "/bk/exhibitions/$slug": {
      "filePath": "bk/exhibitions/$slug.tsx",
      "parent": "/bk"
    },
    "/bk/moving-image/$slug": {
      "filePath": "bk/moving-image/$slug.tsx",
      "parent": "/bk"
    },
    "/kyaf/about/history": {
      "filePath": "kyaf/about/history.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/about/vision": {
      "filePath": "kyaf/about/vision.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/activities/$slug": {
      "filePath": "kyaf/activities/$slug.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/artists/$slug": {
      "filePath": "kyaf/artists/$slug.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/blog/$slug": {
      "filePath": "kyaf/blog/$slug.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/exhibitions/$slug": {
      "filePath": "kyaf/exhibitions/$slug.tsx",
      "parent": "/kyaf"
    },
    "/bk/about/": {
      "filePath": "bk/about/index.tsx",
      "parent": "/bk"
    },
    "/bk/activities/": {
      "filePath": "bk/activities/index.tsx",
      "parent": "/bk"
    },
    "/bk/blog/": {
      "filePath": "bk/blog/index.tsx",
      "parent": "/bk"
    },
    "/bk/exhibitions/": {
      "filePath": "bk/exhibitions/index.tsx",
      "parent": "/bk"
    },
    "/bk/moving-image/": {
      "filePath": "bk/moving-image/index.tsx",
      "parent": "/bk"
    },
    "/kyaf/about/": {
      "filePath": "kyaf/about/index.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/activities/": {
      "filePath": "kyaf/activities/index.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/blog/": {
      "filePath": "kyaf/blog/index.tsx",
      "parent": "/kyaf"
    },
    "/kyaf/exhibitions/": {
      "filePath": "kyaf/exhibitions/index.tsx",
      "parent": "/kyaf"
    }
  }
}
ROUTE_MANIFEST_END */
